### PR TITLE
WIP: flagD provider impl

### PR DESCRIPTION
**Pull request by AlexsJones**
Implementing the flagD provider

### CODE REVIEW

**Comment by tamaroning** [comment]
@AlexsJones
Hello, I am thinking of adding flipt provider.
Should you merge this pull request before I work on it?

**Comment by sheepduke** [comment]
@tamaroning I believe Alex is busy on something else, so this PR will not be merged soon.

What is the relationship between flipt and flagd?

**Comment by beeme1mr** [comment]
@sheepduke, flipt is a [feature flag management app](https://www.flipt.io/). We could either close this PR or try and get it in a working condition. Alex was able to get gRPC working in this PR so it could be a nice reference.

**Comment by tamaroning** [comment]
> @tamaroning I believe Alex is busy on something else, so this PR will not be merged soon.
> 
> What is the relationship between flipt and flagd?

I am just concerned about conflicts.
This PR contains changes in the top level directory

**Comment by sheepduke** [comment]
> @sheepduke, flipt is a [feature flag management app](https://www.flipt.io/). We could either close this PR or try and get it in a working condition. Alex was able to get gRPC working in this PR so it could be a nice reference.

I see. I suggest that we close this PR for now because of the huge changes in OpenFeature Rust API. It can be re-opened later or as a reference. 

Please re-open it if you have some other idea.

**Pull request closed without merging**
